version: '3.8'

services:
  telegram-bot:
    container_name: telegram-bot-${BOT_NAME}
    build: .
    volumes:
      - ./config/${BOT_NAME}:/app/config
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 