version: '3.8'

services:
  telegram-bot:
    container_name: telegram-bot-${BOT_NAME}
    build: .
    volumes:
      - ./config/${BOT_NAME}:/app/config
      - ./logs/${BOT_NAME}:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - BOT_NAME=${BOT_NAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RESPONSE_PROBABILITY=${RESPONSE_PROBABILITY}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 